agent {
    data_dir = "/run/spire/data"
    log_level = "DEBUG"
    server_address = "spire-server"
    server_port = "8081"
    socket_path = "/tmp/spire-agent.sock"
    trust_bundle_path = "/run/spire/bundle/bundle.crt"
    trust_domain = "example.org"
}

plugins {
    KeyManager "disk" {
        plugin_data {
            directory = "/run/spire/data"
            keys_path = "/run/spire/data/keys.json"
        }
    }

    WorkloadAttestor "docker" {
        plugin_data {
            used_container_labels = ["com.docker.compose.service"]
        }
    }
}
